/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoramatrices;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Joel
 */
public class Mensaje extends javax.swing.JFrame {

    /**
     * Creates new form Mensaje
     */
    // Dimension de la pantalla del usuario
    Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
    int Width = 400;
    int Height = 180;
    int pantallaWidth = (int) pantalla.getWidth() - Width;
    int pantallaHeight = (int) pantalla.getHeight() - (Height + 50);

    public Mensaje(String mensaje) {
        initComponents();
        // Centrar JFrame
        this.setLocationRelativeTo(null);
        // Dimensionar el JFrame
        this.setBounds(pantallaWidth, pantallaHeight, Width, Height);
        jpanelprincipal.setBackground(new Color(51, 51, 51));
        txtmensaje.setText(mensaje);
        
        // Funcion para ejecutar código despues un tiempo establecido
        Timer timer = new Timer();

        TimerTask tarea = new TimerTask() {
            public void run() {
                ocultarMensaje();
            }

        };
        
        timer.schedule(tarea,2500);
    }

    private Mensaje() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void ocultarMensaje() {
        this.setVisible(false);
        this.dispose();
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelprincipal = new javax.swing.JPanel();
        txtmensaje = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpanelprincipal.setBackground(new java.awt.Color(51, 51, 51));
        jpanelprincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        jpanelprincipal.setForeground(new java.awt.Color(0, 0, 0));
        jpanelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmensaje.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtmensaje.setForeground(new java.awt.Color(204, 51, 0));
        txtmensaje.setText("Error: ");
        jpanelprincipal.add(txtmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 280, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 200)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("○");
        jpanelprincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 110));

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Lato", 1, 80)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("!");
        jpanelprincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mensaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpanelprincipal;
    private javax.swing.JLabel txtmensaje;
    // End of variables declaration//GEN-END:variables
}
