/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoramatrices;

/**
 *
 * @author Joel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    int mouseX, mouseY;

    public Principal() {
        initComponents();
        this.setBounds(0, 0, 1410, 729);
        this.setLocationRelativeTo(null);
//        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelprincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelsuperior = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();
        btnminimizar = new javax.swing.JButton();
        labelprincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1440, 729));

        jpanelprincipal.setBackground(new java.awt.Color(47, 144, 175));
        jpanelprincipal.setForeground(new java.awt.Color(47, 144, 175));
        jpanelprincipal.setPreferredSize(new java.awt.Dimension(600, 400));
        jpanelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoramatrices/Boton.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpanelprincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 300, 80));

        panelsuperior.setBackground(new java.awt.Color(47, 89, 124));
        panelsuperior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelsuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelsuperiorMouseDragged(evt);
            }
        });
        panelsuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelsuperiorMousePressed(evt);
            }
        });
        panelsuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setBackground(new java.awt.Color(47, 89, 124));
        btnsalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(204, 204, 204));
        btnsalir.setText("×");
        btnsalir.setBorder(null);
        btnsalir.setBorderPainted(false);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setFocusPainted(false);
        btnsalir.setPreferredSize(new java.awt.Dimension(15, 22));
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        panelsuperior.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1363, 0, 50, -1));

        btnminimizar.setBackground(new java.awt.Color(47, 89, 124));
        btnminimizar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btnminimizar.setForeground(new java.awt.Color(204, 204, 204));
        btnminimizar.setText("—");
        btnminimizar.setBorder(null);
        btnminimizar.setBorderPainted(false);
        btnminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnminimizar.setFocusPainted(false);
        btnminimizar.setPreferredSize(new java.awt.Dimension(15, 22));
        btnminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnminimizarMouseExited(evt);
            }
        });
        btnminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizarActionPerformed(evt);
            }
        });
        panelsuperior.add(btnminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 45, 20));

        jpanelprincipal.add(panelsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 20));

        labelprincipal.setBackground(new java.awt.Color(47, 89, 124));
        labelprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoramatrices/Fondo Calculadora Matricial.png"))); // NOI18N
        jpanelprincipal.add(labelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 729));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1424, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpanelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpanelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Calculadora().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelsuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsuperiorMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_panelsuperiorMousePressed

    private void panelsuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsuperiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_panelsuperiorMouseDragged

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
        btnsalir.setBackground(new java.awt.Color(240, 0, 0));
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
        btnsalir.setBackground(new java.awt.Color(47, 89, 124));
    }//GEN-LAST:event_btnsalirMouseExited

    private void btnminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseEntered
        // TODO add your handling code here:
        btnminimizar.setBackground(new java.awt.Color(60, 100, 140));
    }//GEN-LAST:event_btnminimizarMouseEntered

    private void btnminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseExited
        // TODO add your handling code here:
        btnminimizar.setBackground(new java.awt.Color(47, 89, 124));
    }//GEN-LAST:event_btnminimizarMouseExited

    private void btnminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_btnminimizarActionPerformed

    private void btnminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseClicked
        // TODO add your handling code here:
        btnminimizar.setBackground(new java.awt.Color(60, 100, 140));
    }//GEN-LAST:event_btnminimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnminimizar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jpanelprincipal;
    private javax.swing.JLabel labelprincipal;
    private javax.swing.JPanel panelsuperior;
    // End of variables declaration//GEN-END:variables
}
